version: '3.9'
services:
  frontend_service:
    container_name: app-frontend
    build: ./frontend
    ports:
      - 3070:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      backend_service:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3070']
      timeout: 10s
      retries: 5
    networks:
      - virtual-network-1
  backend_service:
    container_name: app-backend
    build: ./backend
    ports:
      - 3071:3071
    platform: linux/x86_64
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      db_service:
        condition: service_healthy
    environment:
      - SERVER_PORT=3071
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db_service
      - DB_PORT=3306
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3071']
      timeout: 10s
      retries: 5
    networks:
      - virtual-network-1
      - virtual-network-2
  db_service:
    image: mysql:8.0.21
    container_name: app-db
    platform: linux/x86_64
    ports:
      - 3072:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    networks:
      - virtual-network-2
volumes:
  db_data:
networks:
  virtual-network-1:
  virtual-network-2:
